name: doc_seg
channels:
- defaults
dependencies:
- bleach=2.1.2=py35_0
- bzip2=1.0.6=h6d464ef_2
- ca-certificates=2017.08.26=h1d4fec5_0
- cairo=1.14.12=h77bcde2_0
- certifi=2018.1.18=py35_0
- cycler=0.10.0=py35hc4d5149_0
- dbus=1.12.2=hd3e2b69_0
- decorator=4.2.1=py35_0
- entrypoints=0.2.3=py35h48174a2_2
- expat=2.2.5=he0dffb1_0
- ffmpeg=3.4=h7264315_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- glib=2.53.6=h5d9569c_2
- gmp=6.1.2=h6c8ec71_1
- graphite2=1.3.10=hf63cedd_1
- gst-plugins-base=1.12.4=h33fb286_0
- gstreamer=1.12.4=hb53b477_0
- harfbuzz=1.7.4=hc5b324e_0
- hdf5=1.10.1=h9caa474_1
- html5lib=1.0.1=py35h2f9c1c0_0
- icu=58.2=h9c2bf20_1
- intel-openmp=2018.0.0=hc7b2577_8
- ipykernel=4.8.0=py35_0
- ipython=6.2.1=py35hd850d2a_1
- ipython_genutils=0.2.0=py35hc9e07d0_0
- ipywidgets=7.1.1=py35_0
- jasper=1.900.1=hd497a04_4
- jedi=0.11.1=py35_0
- jinja2=2.10=py35h480ab6d_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py35h4395190_0
- jupyter=1.0.0=py35hd38625c_0
- jupyter_client=5.2.2=py35_0
- jupyter_console=5.2.0=py35h4044a63_1
- jupyter_core=4.4.0=py35ha89e94b_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libopus=1.2.1=hb9ed12e_0
- libpng=1.6.34=hb9fc6fc_0
- libprotobuf=3.4.1=h5b8497f_0
- libsodium=1.0.15=hf101ebd_0
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.9=h28f6b97_0
- libvpx=1.6.1=h888fd40_0
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.7=h26e45fe_0
- markupsafe=1.0=py35h4f4fcf6_1
- matplotlib=2.1.2=py35h0e671d2_0
- mistune=0.8.3=py35_0
- mkl=2018.0.1=h19d6760_4
- nbconvert=5.3.1=py35hc5194e3_0
- nbformat=4.4.0=py35h12e6e07_0
- ncurses=6.0=h9df7e31_2
- notebook=5.3.1=py35_2
- numpy=1.14.0=py35h3dfced4_1
- opencv=3.3.1=py35h6cbbc71_1
- openssl=1.0.2n=hb7f436b_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py35h1565a15_1
- parso=0.1.1=py35h1b200a3_0
- pcre=8.41=hc27e229_1
- pexpect=4.3.1=py35_0
- pickleshare=0.7.4=py35hd57304d_0
- pip=9.0.1=py35h7e7da9d_4
- pixman=0.34.0=hceecf20_3
- prompt_toolkit=1.0.15=py35hc09de7a_0
- ptyprocess=0.5.2=py35h38ce0a3_0
- pygments=2.2.0=py35h0f41973_0
- pyparsing=2.2.0=py35h041ed72_1
- pyqt=5.6.0=py35h0e41ada_5
- python=3.5.4=h417fded_24
- python-dateutil=2.6.1=py35h90d5b31_1
- pytz=2017.3=py35hb13c558_0
- pyzmq=16.0.3=py35ha889422_0
- qt=5.6.2=h974d657_12
- qtconsole=4.3.1=py35h4626a06_0
- readline=7.0=ha6073c6_4
- scikit-learn=0.19.1=py35hbf1f462_0
- scipy=1.0.0=py35hcbbe4a2_0
- send2trash=1.4.2=py35_0
- setuptools=38.4.0=py35_0
- simplegeneric=0.8.1=py35h2ec4104_0
- sip=4.18.1=py35h9eaea60_2
- six=1.11.0=py35h423b573_1
- sqlite=3.22.0=h1bed415_0
- terminado=0.8.1=py35_0
- testpath=0.3.1=py35had42eaf_0
- tk=8.6.7=hc745277_3
- tornado=4.5.3=py35_0
- tqdm=4.19.4=py35h68e51d2_0
- traitlets=4.3.2=py35ha522a97_0
- wcwidth=0.1.7=py35hcd08066_0
- webencodings=0.5.1=py35hb6cf162_1
- wheel=0.30.0=py35hd3883cf_1
- widgetsnbextension=3.1.0=py35_0
- xz=5.2.3=h55aa19d_2
- zeromq=4.2.2=hbedb6e5_2
- zlib=1.2.11=ha838bed_2
- pip:
  - absl-py==0.1.10
  - better-exceptions==0.2.1
  - docopt==0.6.2
  - enum34==1.1.6
  - futures==3.1.1
  - ipython-genutils==0.2.0
  - jsonpickle==0.9.5
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - markdown==2.6.11
  - munch==2.2.0
  - prompt-toolkit==1.0.15
  - protobuf==3.5.1
  - sacred==0.7.2
  - tensorflow-gpu==1.4.1
  - tensorflow-tensorboard==0.4.0
  - werkzeug==0.14.1
  - wrapt==1.10.11
prefix: /home/seguin/miniconda3/envs/doc_seg

