name: dh_segment
channels:
  - defaults
dependencies:
  - imageio=2.3.0
  - opencv=3.4.1
  - numpy=1.14.5
  - pandas=0.23.0
  - pillow=5.1.0
  - python=3.6
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools=39.1.0
  - shapely=1.6.4
  - tqdm=4.23.3
  - tensorflow-gpu=1.11
  - requests=2.21.0
  - pip:
    - better-exceptions==0.2.1
    - sacred==0.7.3
    - tensorflow-gpu==1.11
    - sphinx==1.8.1
    - sphinx-autodoc-typehints==1.3.0
    - sphinx-rtd-theme==0.4.1
    - sphinxcontrib-bibtex==0.4.0
